/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminSignupRouteImport } from './routes/admin-signup'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackRefRouteImport } from './routes/track.$ref'
import { Route as DriverSignupRouteImport } from './routes/driver.signup'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomerRouteImport } from './routes/_authenticated/customer'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin-signup',
  path: '/admin-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRefRoute = TrackRefRouteImport.update({
  id: '/track/$ref',
  path: '/track/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverSignupRoute = DriverSignupRouteImport.update({
  id: '/driver/signup',
  path: '/driver/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomerRoute = AuthenticatedCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-signup': typeof AdminSignupRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/customer': typeof AuthenticatedCustomerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/api/chat': typeof ApiChatRoute
  '/city/$slug': typeof CitySlugRoute
  '/driver/signup': typeof DriverSignupRoute
  '/track/$ref': typeof TrackRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-signup': typeof AdminSignupRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/customer': typeof AuthenticatedCustomerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/api/chat': typeof ApiChatRoute
  '/city/$slug': typeof CitySlugRoute
  '/driver/signup': typeof DriverSignupRoute
  '/track/$ref': typeof TrackRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-signup': typeof AdminSignupRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/customer': typeof AuthenticatedCustomerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/driver': typeof AuthenticatedDriverRoute
  '/api/chat': typeof ApiChatRoute
  '/city/$slug': typeof CitySlugRoute
  '/driver/signup': typeof DriverSignupRoute
  '/track/$ref': typeof TrackRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-signup'
    | '/auth'
    | '/book'
    | '/admin'
    | '/customer'
    | '/dashboard'
    | '/driver'
    | '/api/chat'
    | '/city/$slug'
    | '/driver/signup'
    | '/track/$ref'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-signup'
    | '/auth'
    | '/book'
    | '/admin'
    | '/customer'
    | '/dashboard'
    | '/driver'
    | '/api/chat'
    | '/city/$slug'
    | '/driver/signup'
    | '/track/$ref'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-signup'
    | '/auth'
    | '/book'
    | '/_authenticated/admin'
    | '/_authenticated/customer'
    | '/_authenticated/dashboard'
    | '/_authenticated/driver'
    | '/api/chat'
    | '/city/$slug'
    | '/driver/signup'
    | '/track/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminSignupRoute: typeof AdminSignupRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ApiChatRoute: typeof ApiChatRoute
  CitySlugRoute: typeof CitySlugRoute
  DriverSignupRoute: typeof DriverSignupRoute
  TrackRefRoute: typeof TrackRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-signup': {
      id: '/admin-signup'
      path: '/admin-signup'
      fullPath: '/admin-signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$ref': {
      id: '/track/$ref'
      path: '/track/$ref'
      fullPath: '/track/$ref'
      preLoaderRoute: typeof TrackRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/signup': {
      id: '/driver/signup'
      path: '/driver/signup'
      fullPath: '/driver/signup'
      preLoaderRoute: typeof DriverSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer': {
      id: '/_authenticated/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AuthenticatedCustomerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCustomerRoute: typeof AuthenticatedCustomerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCustomerRoute: AuthenticatedCustomerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDriverRoute: AuthenticatedDriverRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminSignupRoute: AdminSignupRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ApiChatRoute: ApiChatRoute,
  CitySlugRoute: CitySlugRoute,
  DriverSignupRoute: DriverSignupRoute,
  TrackRefRoute: TrackRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
